#include "bsp_led.h"

void LED_Init(void)
{    	 
	RCC->AHB1ENR|=1<<2;//使能PORTC时钟 
	GPIO_Set(GPIOC,PIN13|PIN14,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_2M,GPIO_PUPD_PU); //PC13,PC14设置
	LED0=1;//LED0关闭
	LED1=1;//LED1关闭
	
//	RCC->AHB1ENR|=1<<4;//使能PORTC时钟 
//	GPIO_Set(GPIOE,PIN5,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_2M,GPIO_PUPD_PU); 
//	PEout(5)=1;	
//	
//	RCC->AHB1ENR|=1<<3;//使能PORTC时钟 
//	GPIO_Set(GPIOD,PIN12,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_2M,GPIO_PUPD_PU); 
//	PDout(12)=1;	
//	
//	RCC->AHB1ENR|=1<<0;//使能PORTC时钟 
//	GPIO_Set(GPIOA,PIN1,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_2M,GPIO_PUPD_PU); 
//	PAout(1)=1;	
//	
//	RCC->AHB1ENR|=1<<0;//使能PORTC时钟 
//	GPIO_Set(GPIOA,PIN8,GPIO_MODE_OUT,GPIO_OTYPE_PP,GPIO_SPEED_2M,GPIO_PUPD_PU); 
//	PAout(8)=1;	
}



